{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-uikit/9999.0.0-SNAPSHOT/ui-uikit-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-uikit",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-uikit-uikitSimArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "ui-uikit-uikitsimarm64-9999.0.0-SNAPSHOT.klib",
          "size": 48834,
          "sha512": "d132f0ff5c2ec5eef25be4cee904cb66e8a66f8aac58eb387e1b0f471f713c2f0d00f4124a244289c7661f513de0adf3a4ea5a7c1f4be0f42fcea21352e75c84",
          "sha256": "c8e9b02f4c3ca02b3fcbc88db2506aaa93e917479955433e4209d1eb44b26402",
          "sha1": "791e10d1205dd368a03aecbbafb2df9444fb95cf",
          "md5": "5f08beebcffe291c9d5a820d022d637b"
        },
        {
          "name": "ui-uikit-uikitSimArm64Cinterop-utilsMain-9999.0.0-SNAPSHOT.klib",
          "url": "ui-uikit-uikitsimarm64-9999.0.0-SNAPSHOT-cinterop-utils.klib",
          "size": 18584,
          "sha512": "3cdd279c5ec8822044a81aa95507df299e576f5443f75ad56672af51feab12a71711d4f094314e2f9ee698d8ace0b2336661aff35b130f2a1f153f490701e353",
          "sha256": "86727c7046c86408dcd2f8513c0b04437a4df362a4b63c3650855a5181b700e8",
          "sha1": "77bf1b2001e50ce426a5a51ee706eb989239f99a",
          "md5": "cdcd203b3f5d27b751af952dfee43881"
        }
      ]
    },
    {
      "name": "uikitSimArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-uikit-uikitsimarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-uikit-uikitsimarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 1490,
          "sha512": "d6dc3e7f01c622f0ea48c15b68dd3bd723a920b41f0b1cc815a262f8c90d27005f8dce99adc3b3ccf4812250ef7e74cf35479950fdf71a195a45d93ba5acbdb3",
          "sha256": "b786874f6ed58f0ba4b5a0c2e47b7361c73b1aaab5f7eb1d608a026944a86265",
          "sha1": "aba8ee840667a30a5ec3805304797479188efcc4",
          "md5": "740df642ae42cb3d618bbb1f1d5693f3"
        }
      ]
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-uikit-uikitsimarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "ui-uikit-uikitsimarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 30156,
          "sha512": "4eb24a5db64bc3767a01452e2972b16373c5e831db1b37b93004c4402d508de80cfe9a5d2af874b76bf7dc31d06a12e9b5a2c9026fdb8bfc776f24801a175747",
          "sha256": "4b612850c62b58c024dd7b40d00f0bdc9ec4984126b53b0e172644bf5e8f4358",
          "sha1": "55fd678bcada552e2f9783bdd60316082e194105",
          "md5": "edadb9af35de09c93c019a119fd783dd"
        }
      ]
    }
  ]
}