{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling-preview/1.10.3-picture-cache.2/ui-tooling-preview-1.10.3-picture-cache.2.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.10.3-picture-cache.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-uikitArm64Main-1.10.3-picture-cache.2.klib",
          "url": "ui-tooling-preview-uikitarm64-1.10.3-picture-cache.2.klib",
          "size": 38266,
          "sha512": "539d776b1eb8db85fce1ee4ad53625323dba7187332a1f15d6df91fc21f5b1e879d26a8f79451efbac0feebcc4bfe168908f07e1742b0b825cbe7819f83abcbe",
          "sha256": "fc3ffb6ded110039db1691ec2ad81ddf5a8f5a99849e3128bf5b27c9bc1d3c45",
          "sha1": "36de148c7d2d6d7edfe6a7e01c050bee01d88b5f",
          "md5": "54cd928a9186f9f36dc239f34b1e14da"
        }
      ]
    },
    {
      "name": "uikitArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-tooling-preview-uikitarm64-1.10.3-picture-cache.2-sources.jar",
          "url": "ui-tooling-preview-uikitarm64-1.10.3-picture-cache.2-sources.jar",
          "size": 14792,
          "sha512": "7e81a8b72d4bf301060ba249e473e5cb09cbab322d2ad529a52a2a24016f73d71dc485cbe2cabf11a396de93615d90e081c455519d623c34f0cdeca225386829",
          "sha256": "b2038f7dd5180f2daa1231af8ea15afa21fce47df690633f3f43c25e9420c7d9",
          "sha1": "735f70e90bb515403838df821119a3216e7311aa",
          "md5": "4f2f7d345181895b6a872b4e281f108a"
        }
      ]
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-uikitarm64-1.10.3-picture-cache.2-metadata.jar",
          "url": "ui-tooling-preview-uikitarm64-1.10.3-picture-cache.2-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}