{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.10.3-picture-cache.1/runtime-1.10.3-picture-cache.1.module",
    "group": "org.jetbrains.compose.runtime",
    "module": "runtime",
    "version": "1.10.3-picture-cache.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-uikitX64Main-1.10.3-picture-cache.1.klib",
          "url": "runtime-uikitx64-1.10.3-picture-cache.1.klib",
          "size": 3191,
          "sha512": "a94d168f952f1cd453dad5d2dffe24c47d180c3204714ac5116b1dd5d0f3de88927524bb3c54d04f7d6a15cf69fd5803285cca240e12af90e7c609c4363b9607",
          "sha256": "36acb97b19a0bca0181fcb763c81274f3a13ad39587ad8111239f2a66ce9dc8a",
          "sha1": "39e9d47241c2d4b02864d8ef1490d7f0b56f230b",
          "md5": "c93896e16c88c74ca82885d4319bfc97"
        }
      ]
    },
    {
      "name": "uikitX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-uikitx64-1.10.3-picture-cache.1-sources.jar",
          "url": "runtime-uikitx64-1.10.3-picture-cache.1-sources.jar",
          "size": 1141,
          "sha512": "ccba4d9d5523034b910bf1cfe65b9d5adf77e6540729724533210de338099a52db64249a9f620f8bbdc0342e84713b5baca2b510a2e56a91b845c07d259aab37",
          "sha256": "6f27472e1e5fe26259f156b498f6745feb57b651b673d65fe9938a7fec2d9065",
          "sha1": "b557946ae7e4f6be395dca186f61b64f4766ce6a",
          "md5": "a2ed51ed351ce630c721aa35c255c2a2"
        }
      ]
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-uikitx64-1.10.3-picture-cache.1-metadata.jar",
          "url": "runtime-uikitx64-1.10.3-picture-cache.1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}