{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.material",
    "module": "material-navigation",
    "version": "1.10.3-picture-cache.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material-navigation-1.10.3-picture-cache.2.jar",
          "url": "material-navigation-1.10.3-picture-cache.2.jar",
          "size": 9033,
          "sha512": "4c2e7a4f89a6f988d079d4e116b9a5d400c2b166bd41bc070268486887bc30bf47d2e4db0a63a03c5eab889057e4737ae4ca078e38ef369c8fbaefaa19b93c93",
          "sha256": "58fae11c07419e3bbaf31a5467a50290eaaa8ac2d28041c421f30ceff2f6f6d8",
          "sha1": "25b4e414e9977d9f323e7c0633e6bd95e8141bd0",
          "md5": "60c7b99e3e9988b3dd75779f320df274"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "material-navigation-1.10.3-picture-cache.2-sources.jar",
          "url": "material-navigation-1.10.3-picture-cache.2-sources.jar",
          "size": 12012,
          "sha512": "b89e05be48bb53666317cc9255d15a81d42ea5dbf96e049e2838228b08651de1bf41221d9855f7cc730abb0e525ff8d7eafd81b206bfd20bd5a0c09c3038d9cc",
          "sha256": "65a5912922822d3371bcaa78403e3ca24474e9873bdbe82c4f7f60c2a3f584e4",
          "sha1": "1dd882f9a1c58e5c5276a0723a46d5921e4acd83",
          "md5": "4c4664955adfd9c8b8bed1766b2aca32"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-navigation",
          "version": {
            "requires": "1.10.3"
          }
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-navigation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ]
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-navigation",
          "version": {
            "requires": "1.10.3"
          }
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-navigation",
          "version": {
            "requires": "1.10.3"
          }
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-navigation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-navigation",
          "version": {
            "requires": "1.10.3"
          }
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-navigation-desktop/1.10.3-picture-cache.2/material-navigation-desktop-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-desktop",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-navigation-desktop/1.10.3-picture-cache.2/material-navigation-desktop-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-desktop",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-navigation-desktop/1.10.3-picture-cache.2/material-navigation-desktop-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-desktop",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../material-navigation-js/1.10.3-picture-cache.2/material-navigation-js-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-js",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../material-navigation-js/1.10.3-picture-cache.2/material-navigation-js-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-js",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../material-navigation-js/1.10.3-picture-cache.2/material-navigation-js-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-js",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-macosarm64/1.10.3-picture-cache.2/material-navigation-macosarm64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-macosarm64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-macosarm64/1.10.3-picture-cache.2/material-navigation-macosarm64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-macosarm64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-macosarm64/1.10.3-picture-cache.2/material-navigation-macosarm64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-macosarm64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-macosx64/1.10.3-picture-cache.2/material-navigation-macosx64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-macosx64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-macosx64/1.10.3-picture-cache.2/material-navigation-macosx64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-macosx64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-macosx64/1.10.3-picture-cache.2/material-navigation-macosx64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-macosx64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-uikitarm64/1.10.3-picture-cache.2/material-navigation-uikitarm64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-uikitarm64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "uikitArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-uikitarm64/1.10.3-picture-cache.2/material-navigation-uikitarm64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-uikitarm64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-uikitarm64/1.10.3-picture-cache.2/material-navigation-uikitarm64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-uikitarm64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-uikitsimarm64/1.10.3-picture-cache.2/material-navigation-uikitsimarm64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-uikitsimarm64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "uikitSimArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-uikitsimarm64/1.10.3-picture-cache.2/material-navigation-uikitsimarm64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-uikitsimarm64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-uikitsimarm64/1.10.3-picture-cache.2/material-navigation-uikitsimarm64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-uikitsimarm64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-uikitx64/1.10.3-picture-cache.2/material-navigation-uikitx64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-uikitx64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "uikitX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-uikitx64/1.10.3-picture-cache.2/material-navigation-uikitx64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-uikitx64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-navigation-uikitx64/1.10.3-picture-cache.2/material-navigation-uikitx64-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-uikitx64",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../material-navigation-wasm-js/1.10.3-picture-cache.2/material-navigation-wasm-js-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-wasm-js",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../material-navigation-wasm-js/1.10.3-picture-cache.2/material-navigation-wasm-js-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-wasm-js",
        "version": "1.10.3-picture-cache.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../material-navigation-wasm-js/1.10.3-picture-cache.2/material-navigation-wasm-js-1.10.3-picture-cache.2.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-navigation-wasm-js",
        "version": "1.10.3-picture-cache.2"
      }
    }
  ]
}