{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-backhandler/1.10.3-picture-cache.1/ui-backhandler-1.10.3-picture-cache.1.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-backhandler",
    "version": "1.10.3-picture-cache.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-backhandler-uikitArm64Main-1.10.3-picture-cache.1.klib",
          "url": "ui-backhandler-uikitarm64-1.10.3-picture-cache.1.klib",
          "size": 22765,
          "sha512": "c7071d212ee1c0e840c9b981c5bc2e064dc7e12a1cf6a923042996956945e71c0fa16d13b5cb0042c5574e4c696b58eda3f6e79f7ae6eea96e3d3fe9c82def97",
          "sha256": "485c6650065a34645fd264b17f1197e035333bbc24f2d4b60ebd55b5f8ad8d3e",
          "sha1": "3f4bac21d9ab28d4ecdae5f0be714f27d360c12a",
          "md5": "096a9c0497c5bf06e0ed462c0118dd73"
        }
      ]
    },
    {
      "name": "uikitArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-backhandler-uikitarm64-1.10.3-picture-cache.1-sources.jar",
          "url": "ui-backhandler-uikitarm64-1.10.3-picture-cache.1-sources.jar",
          "size": 6999,
          "sha512": "474d13d744bb6e06c082789f99798bc91383210ac7d14c5d9eace3c20bf6e8db689abc6e375687ad658a7163496360f763b07939e3a1012c96032d9e2973d4cc",
          "sha256": "38dbbb0950845a8c579436ecc5aa1088010f60fc05bb7ae8e1c2679cb7985c82",
          "sha1": "7d14f6fe2e25f5ccba5a986bdc1724ca7725ecc7",
          "md5": "3c0c09e86c4d8f22aa423eb030aae4c3"
        }
      ]
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-backhandler-uikitarm64-1.10.3-picture-cache.1-metadata.jar",
          "url": "ui-backhandler-uikitarm64-1.10.3-picture-cache.1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}