{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/1.10.3-picture-cache.2/material-ripple-1.10.3-picture-cache.2.module",
    "group": "org.jetbrains.compose.material",
    "module": "material-ripple",
    "version": "1.10.3-picture-cache.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-desktop-1.10.3-picture-cache.2.jar",
          "url": "material-ripple-desktop-1.10.3-picture-cache.2.jar",
          "size": 73535,
          "sha512": "6cdf6d5ed3a848260a0b27eeffc9cf8fb1f7a666cc8d5331744a366e867f2025d48657fedf3fcb3c73e12b4233f182c4b170bb763f845feaa3483581888022b2",
          "sha256": "3257697a1a58188ec3dc31f31867f1c38209900b87df1261ebac9e6a1387db83",
          "sha1": "74a14824f086339703264689c5a7cf4ceb39ed40",
          "md5": "24324c2656b22bad47558022bfc18265"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-desktop-1.10.3-picture-cache.2.jar",
          "url": "material-ripple-desktop-1.10.3-picture-cache.2.jar",
          "size": 73535,
          "sha512": "6cdf6d5ed3a848260a0b27eeffc9cf8fb1f7a666cc8d5331744a366e867f2025d48657fedf3fcb3c73e12b4233f182c4b170bb763f845feaa3483581888022b2",
          "sha256": "3257697a1a58188ec3dc31f31867f1c38209900b87df1261ebac9e6a1387db83",
          "sha1": "74a14824f086339703264689c5a7cf4ceb39ed40",
          "md5": "24324c2656b22bad47558022bfc18265"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "material-ripple-desktop-1.10.3-picture-cache.2-sources.jar",
          "url": "material-ripple-desktop-1.10.3-picture-cache.2-sources.jar",
          "size": 15269,
          "sha512": "74fa1de4d5b538cdf1649a5d3d6d0b3577b64b6b2db1836319dbc50a16a74c7fc5865625189ae62200deab39944561d80d131574e233621de3804acbfbb9ecee",
          "sha256": "925a415f7b0472ce74f50a7b7c457348016f1f7642afcc5ac2488ab5efd8d23a",
          "sha1": "2b1d7b769dfd53c82e7e225aa5409ac889aaa150",
          "md5": "90ed31fb7e33bfdd1c232be709066733"
        }
      ]
    }
  ]
}