{
  "formatVersion": "1.1",
  "component": {
    "url": "../../adaptive-navigation3/9999.0.0-SNAPSHOT/adaptive-navigation3-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material3.adaptive",
    "module": "adaptive-navigation3",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation3-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "adaptive-navigation3-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 55259,
          "sha512": "aeedbc39105e0efabe99dfbabb49e0a17c7da82adcf93dbdc7f7b69fd647adfb40640c8ad09c4a8f08a87b0b0dc1df7cc1dcd5a0f321cf28f47feef3d56a4951",
          "sha256": "1e1ab17ba9724233f9a8abb8b004bb4fa6c000656acb1f60a145963d2fee9657",
          "sha1": "5101bcdc827513ef3e92f7982eef3b3251cb5f7d",
          "md5": "56075a0742ebe760401a464c258c782f"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation3-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "adaptive-navigation3-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 55259,
          "sha512": "aeedbc39105e0efabe99dfbabb49e0a17c7da82adcf93dbdc7f7b69fd647adfb40640c8ad09c4a8f08a87b0b0dc1df7cc1dcd5a0f321cf28f47feef3d56a4951",
          "sha256": "1e1ab17ba9724233f9a8abb8b004bb4fa6c000656acb1f60a145963d2fee9657",
          "sha1": "5101bcdc827513ef3e92f7982eef3b3251cb5f7d",
          "md5": "56075a0742ebe760401a464c258c782f"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "adaptive-navigation3-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "url": "adaptive-navigation3-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "size": 10109,
          "sha512": "2ca3aebdee5358e948fa9b5784eb926c7af3e4fe956eaf08879f5a50fc839a3115c5b316e77faecea9cd93c447582843e4f4581e2dafe6f13355201521686862",
          "sha256": "4e150f056f71370f5a8fc3674f97753101481c91018bd24b07b82268722f8499",
          "sha1": "fa3cc013177dba60f8db39558b4320b8bced5ccc",
          "md5": "cb06b5983f11dda7aba1490acffcafe9"
        }
      ]
    }
  ]
}