{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling/1.10.3-picture-cache.2/ui-tooling-1.10.3-picture-cache.2.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-tooling",
    "version": "1.10.3-picture-cache.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-desktop-1.10.3-picture-cache.2.jar",
          "url": "ui-tooling-desktop-1.10.3-picture-cache.2.jar",
          "size": 23513,
          "sha512": "1ca26149190d15a0304d0f01cc0a121e50fb1ffee787ca9c9c009f0f1ad549f9860ae418142dc106c1f9dc32e27427fcbaedcf4f92e4bd79023acf91d28744d0",
          "sha256": "18b0053ddfa51ce54a3bd52e7e72c5fb8acd847bac35c17d551b69798d265601",
          "sha1": "1aca5f3a10f0ebc13165981004166c8549a24bad",
          "md5": "280c1c4daae3a81493560de1c802c293"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-desktop-1.10.3-picture-cache.2.jar",
          "url": "ui-tooling-desktop-1.10.3-picture-cache.2.jar",
          "size": 23513,
          "sha512": "1ca26149190d15a0304d0f01cc0a121e50fb1ffee787ca9c9c009f0f1ad549f9860ae418142dc106c1f9dc32e27427fcbaedcf4f92e4bd79023acf91d28744d0",
          "sha256": "18b0053ddfa51ce54a3bd52e7e72c5fb8acd847bac35c17d551b69798d265601",
          "sha1": "1aca5f3a10f0ebc13165981004166c8549a24bad",
          "md5": "280c1c4daae3a81493560de1c802c293"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-tooling-desktop-1.10.3-picture-cache.2-sources.jar",
          "url": "ui-tooling-desktop-1.10.3-picture-cache.2-sources.jar",
          "size": 9684,
          "sha512": "4d9b0626f59c57a1eae87d364f5e0ddbd78bff0b2ee7ed7ca8651379ec9d311fa90f2389c1d0ee9adc81aef169a204f10a49f1635aace40de245759246cd27a8",
          "sha256": "9c4d745dffa6b76a5af455e421d7d0cacd8355fad92fa6869baffa004a5e229a",
          "sha1": "473c14fb4478952a2e331d69f34d513189e38440",
          "md5": "a24f7747e044ddb61f0237305afa0562"
        }
      ]
    }
  ]
}