{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation/9999.0.0-SNAPSHOT/animation-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "animation-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "animation-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 374782,
          "sha512": "5ac6473d96c1f6d7ff46b2df07b11d4780ad6e2a179aa543bede63ddad9cc0f5e76f0318c79c64487c1269a62b4ff657b5b986d6ae1b2e4d495cc7eb4495f420",
          "sha256": "1881c5575440055d54a679418f7ad7e86c0349743389360bed0f6a36af16ba34",
          "sha1": "52a17b8bd5f608cdb60f01c64eee2830b8484ca7",
          "md5": "d75724d60eb8bef206a6affbebcbada5"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "animation-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "animation-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 374782,
          "sha512": "5ac6473d96c1f6d7ff46b2df07b11d4780ad6e2a179aa543bede63ddad9cc0f5e76f0318c79c64487c1269a62b4ff657b5b986d6ae1b2e4d495cc7eb4495f420",
          "sha256": "1881c5575440055d54a679418f7ad7e86c0349743389360bed0f6a36af16ba34",
          "sha1": "52a17b8bd5f608cdb60f01c64eee2830b8484ca7",
          "md5": "d75724d60eb8bef206a6affbebcbada5"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "animation-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "url": "animation-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "size": 92240,
          "sha512": "3fab3afb23671f3cab0f4ed42659c2eca25f9beb0865446bf04a5d8f3f93ed490753172bdce1ea7c9b65dc58fb2ae1cd939f1a9e53ba38a5340c080a89c1bf7a",
          "sha256": "5252f29c4e04440660cbc3ddc02211a01b9560ed9593c851cc8a2591359538aa",
          "sha1": "954f84281245dce437793c44c21b3d973c1844a3",
          "md5": "c34a2e4e1fdebe97db9a20cf4c8b3dc6"
        }
      ]
    }
  ]
}