{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material/1.10.3-picture-cache.1/material-1.10.3-picture-cache.1.module",
    "group": "org.jetbrains.compose.material",
    "module": "material",
    "version": "1.10.3-picture-cache.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material-uikitSimArm64Main-1.10.3-picture-cache.1.klib",
          "url": "material-uikitsimarm64-1.10.3-picture-cache.1.klib",
          "size": 1479369,
          "sha512": "d6ec36284db520d8c3d08a40372124efd0fb9d73f4312068df6b5a8590dc64f1f64e7836ca0b0052e4a2fd7c75104ac51ef5854830d3b692a4c61cb9ef387c1d",
          "sha256": "9a5b744ec1babebed40becb56e36de3611f4f3a503ccf8d258e8939180162f31",
          "sha1": "35002eeeb1dd1cb270a2426f0e61d0591ffa99ad",
          "md5": "62d1e4995294b67464c57de36fcfcfe9"
        }
      ]
    },
    {
      "name": "uikitSimArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "material-uikitsimarm64-1.10.3-picture-cache.1-sources.jar",
          "url": "material-uikitsimarm64-1.10.3-picture-cache.1-sources.jar",
          "size": 324234,
          "sha512": "496e16092d85ddeb1a6c69890424c93536a05fdf7fc7bbf6823e2d7e0ec12199f52e9cc266ad386692b6a2e428bc9e1ee54c8ede8cf20b9790cc2792d0ae0aa9",
          "sha256": "322aade7e40873e98dd73ea0ede7457b3708ffc3e67c650fe89db56f3a7523a0",
          "sha1": "4adadbdecf557b57bbd7f6c99416b949cdd0d088",
          "md5": "b51837a8bad18407515460a6d03aedaf"
        }
      ]
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material-uikitsimarm64-1.10.3-picture-cache.1-metadata.jar",
          "url": "material-uikitsimarm64-1.10.3-picture-cache.1-metadata.jar",
          "size": 3170,
          "sha512": "95066b9dce9e403265ea4894ffe0a68c1bd5be010a25ebc06e60c1a237c85c952ff37fd9daefbf2e33ab8ca922306c7473998bd37f5c7987b744a83b274d5598",
          "sha256": "7d2c3030da44ba90591cb645d8808824a1ebf52865cebecee9d8fa0e82286e54",
          "sha1": "62fede04648990960606c02512100b8b2be4f574",
          "md5": "17c60ed884ddb602c6d0823f95f4f3bb"
        }
      ]
    }
  ]
}