{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-navigation/1.10.3-picture-cache.1/material-navigation-1.10.3-picture-cache.1.module",
    "group": "org.jetbrains.compose.material",
    "module": "material-navigation",
    "version": "1.10.3-picture-cache.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "material-navigation-desktop-1.10.3-picture-cache.1.jar",
          "url": "material-navigation-desktop-1.10.3-picture-cache.1.jar",
          "size": 44014,
          "sha512": "aa04fd4514325b49cf467279e5147fbee856ae831160f6ba48a023d43573bec15c57dc5ed3223fbf98a0a61e4fcdece6d3853df94e47d04b63813dcf0c19508f",
          "sha256": "cc76332fa09fb146097da3cd237da070bfd6489d856f38e19c10c29961a56f37",
          "sha1": "77af20b9de7a5ffdecc9a483707aeefb67efa8b4",
          "md5": "223d7e0f742c9b1cd93a2074447e8964"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material-navigation-desktop-1.10.3-picture-cache.1.jar",
          "url": "material-navigation-desktop-1.10.3-picture-cache.1.jar",
          "size": 44014,
          "sha512": "aa04fd4514325b49cf467279e5147fbee856ae831160f6ba48a023d43573bec15c57dc5ed3223fbf98a0a61e4fcdece6d3853df94e47d04b63813dcf0c19508f",
          "sha256": "cc76332fa09fb146097da3cd237da070bfd6489d856f38e19c10c29961a56f37",
          "sha1": "77af20b9de7a5ffdecc9a483707aeefb67efa8b4",
          "md5": "223d7e0f742c9b1cd93a2074447e8964"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "material-navigation-desktop-1.10.3-picture-cache.1-sources.jar",
          "url": "material-navigation-desktop-1.10.3-picture-cache.1-sources.jar",
          "size": 12012,
          "sha512": "b89e05be48bb53666317cc9255d15a81d42ea5dbf96e049e2838228b08651de1bf41221d9855f7cc730abb0e525ff8d7eafd81b206bfd20bd5a0c09c3038d9cc",
          "sha256": "65a5912922822d3371bcaa78403e3ca24474e9873bdbe82c4f7f60c2a3f584e4",
          "sha1": "1dd882f9a1c58e5c5276a0723a46d5921e4acd83",
          "md5": "4c4664955adfd9c8b8bed1766b2aca32"
        }
      ]
    }
  ]
}