{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-uikit/9999.0.0-SNAPSHOT/ui-uikit-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-uikit",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-uikit-uikitArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "ui-uikit-uikitarm64-9999.0.0-SNAPSHOT.klib",
          "size": 48745,
          "sha512": "d3d444d97a556715df634fff884b002f8dd3025b868e82ee94fdec1f378939a1550c7e552782f546b204c84dcc1b332bb21bfa95ec62ec9a9f3ffc3770b157be",
          "sha256": "43b9c671aa51d1d01f59e33a2f487a6acd9953ca092a27a92470bebd973d589c",
          "sha1": "63b03b3be912f9afe6295c3d10ee0f8610f5b60e",
          "md5": "dda1e3ad0855059511475f1e6db41c6d"
        },
        {
          "name": "ui-uikit-uikitArm64Cinterop-utilsMain-9999.0.0-SNAPSHOT.klib",
          "url": "ui-uikit-uikitarm64-9999.0.0-SNAPSHOT-cinterop-utils.klib",
          "size": 17822,
          "sha512": "e88d3f2f79f83b07fe90b2830647b7ac32fcdfe1bc7cc79b96e69f2dcbe17e794d951a73ab163927a8adb7f5f180004ab5f5be640c7964970ffd6630f6ec7076",
          "sha256": "52350af8609340678792120a8876f33153371efabe37561d9a9625cb4db58656",
          "sha1": "131b418f6309a6e533cf7ff0a4a8910a4ae18d0f",
          "md5": "22e2052400309f7c43d2a04b8ba6a188"
        }
      ]
    },
    {
      "name": "uikitArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-uikit-uikitarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-uikit-uikitarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 1490,
          "sha512": "d6dc3e7f01c622f0ea48c15b68dd3bd723a920b41f0b1cc815a262f8c90d27005f8dce99adc3b3ccf4812250ef7e74cf35479950fdf71a195a45d93ba5acbdb3",
          "sha256": "b786874f6ed58f0ba4b5a0c2e47b7361c73b1aaab5f7eb1d608a026944a86265",
          "sha1": "aba8ee840667a30a5ec3805304797479188efcc4",
          "md5": "740df642ae42cb3d618bbb1f1d5693f3"
        }
      ]
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-uikit-uikitarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "ui-uikit-uikitarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 30156,
          "sha512": "4eb24a5db64bc3767a01452e2972b16373c5e831db1b37b93004c4402d508de80cfe9a5d2af874b76bf7dc31d06a12e9b5a2c9026fdb8bfc776f24801a175747",
          "sha256": "4b612850c62b58c024dd7b40d00f0bdc9ec4984126b53b0e172644bf5e8f4358",
          "sha1": "55fd678bcada552e2f9783bdd60316082e194105",
          "md5": "edadb9af35de09c93c019a119fd783dd"
        }
      ]
    }
  ]
}