{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-unit/9999.0.0-SNAPSHOT/ui-unit-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-unit",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-uikitX64Main-9999.0.0-SNAPSHOT.klib",
          "url": "ui-unit-uikitx64-9999.0.0-SNAPSHOT.klib",
          "size": 104731,
          "sha512": "eba81518fa240748a70e9363bce827c0ffc3cbf5e78808d9be5784cbcf863b9ef40b027ebbd8fe651fd664e36a7acad9e809dc92d628b906b26136398ecd3c73",
          "sha256": "a340b9668ec1ae9b635a3e7cd86e3b641790fb3914d288701667e66e91c3fe88",
          "sha1": "aeafcaa11e912f3afce903062070f0caa0e8d015",
          "md5": "0e5502cabbc4210045e1b48ca9025a3c"
        }
      ]
    },
    {
      "name": "uikitX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-unit-uikitx64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-unit-uikitx64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 33594,
          "sha512": "360e2fc9c8f62bba86f0e928ff8f61087149b616c1335b58f200bb73fabbbde88e6f3dfd6bc9ac28ffc72df4bce35618f3f0261460d1ef17dc28ee9f255db466",
          "sha256": "fabed03aa9375fac42c9f4dc8f13734c500950371904a6f2eaf22b3b2a088c42",
          "sha1": "552859ce495664d56726fde8c4c1f3a772ddcf05",
          "md5": "0d2f081da1941af2510c011841671769"
        }
      ]
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-uikitx64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "ui-unit-uikitx64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}