{
  "formatVersion": "1.1",
  "component": {
    "url": "../../adaptive-navigation/9999.0.0-SNAPSHOT/adaptive-navigation-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material3.adaptive",
    "module": "adaptive-navigation",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "adaptive-navigation-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 21530,
          "sha512": "58770b249a5eb3c98987a34b8675cf11f2661af093218566dd790638934e684c2d31d3a06ff147d6a29909c3e5f87c82dfff469dbdfd850a07c9c09262c45764",
          "sha256": "aa57c995a6bd386dbf3ce7d76ccad04543449adb7593db4b9bf82c7ae973a4a0",
          "sha1": "1d06e5479c773ce586f328dbe9cca7c7d54b0fcb",
          "md5": "2b828501cd66c66e05bdea3b39b94c4d"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "adaptive-navigation-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 21530,
          "sha512": "58770b249a5eb3c98987a34b8675cf11f2661af093218566dd790638934e684c2d31d3a06ff147d6a29909c3e5f87c82dfff469dbdfd850a07c9c09262c45764",
          "sha256": "aa57c995a6bd386dbf3ce7d76ccad04543449adb7593db4b9bf82c7ae973a4a0",
          "sha1": "1d06e5479c773ce586f328dbe9cca7c7d54b0fcb",
          "md5": "2b828501cd66c66e05bdea3b39b94c4d"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "adaptive-navigation-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "url": "adaptive-navigation-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "size": 7011,
          "sha512": "f608eee6009186da15c86c578c9b2e14dba90211f822863bc619070b71a32f369867baf9b1971a6462c3e9791fe400a2bd339525a27a5e94dbb5843dc0cd58ad",
          "sha256": "eb9d87a6bf8704e2f83f7c7d163c964e690963fb085c489a07e639a5a070b5e2",
          "sha1": "80ce7864efedd15f7e1a04a048319a5d3d45e315",
          "md5": "cc97ad02c66e4dfdc141d2c6fd1a0ba2"
        }
      ]
    }
  ]
}