{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-saveable/1.10.3-picture-cache.1/runtime-saveable-1.10.3-picture-cache.1.module",
    "group": "org.jetbrains.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.10.3-picture-cache.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-uikitX64Main-1.10.3-picture-cache.1.klib",
          "url": "runtime-saveable-uikitx64-1.10.3-picture-cache.1.klib",
          "size": 3281,
          "sha512": "51b51d56e92535befe519031b5b373b66440cd2deabd78cdb51e793e2545bf15f005004459d4800de78fbb4c339fccafcd20205218a7d0834c6ae96d91a08071",
          "sha256": "ac9e33ad2beb0bba4c98cc2c93c15a4c607ec27e77c4bb43aeb8555511882757",
          "sha1": "4cd63b66c982420b9ee449153915d546ab68ea09",
          "md5": "9c2e5959f3ce08d747ac11d4cb04fad5"
        }
      ]
    },
    {
      "name": "uikitX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-saveable-uikitx64-1.10.3-picture-cache.1-sources.jar",
          "url": "runtime-saveable-uikitx64-1.10.3-picture-cache.1-sources.jar",
          "size": 1141,
          "sha512": "ccba4d9d5523034b910bf1cfe65b9d5adf77e6540729724533210de338099a52db64249a9f620f8bbdc0342e84713b5baca2b510a2e56a91b845c07d259aab37",
          "sha256": "6f27472e1e5fe26259f156b498f6745feb57b651b673d65fe9938a7fec2d9065",
          "sha1": "b557946ae7e4f6be395dca186f61b64f4766ce6a",
          "md5": "a2ed51ed351ce630c721aa35c255c2a2"
        }
      ]
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-uikitx64-1.10.3-picture-cache.1-metadata.jar",
          "url": "runtime-saveable-uikitx64-1.10.3-picture-cache.1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}