{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-unit/1.10.3-picture-cache.2/ui-unit-1.10.3-picture-cache.2.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-unit",
    "version": "1.10.3-picture-cache.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-macosX64Main-1.10.3-picture-cache.2.klib",
          "url": "ui-unit-macosx64-1.10.3-picture-cache.2.klib",
          "size": 104731,
          "sha512": "2f06d191c483ee6524aa62ca306cb7d0ef6b80c345771951b8bc40b95dafcd22b93fd852b88ebf4969b2405583baa5d3896dcd51216db7797ec0d7fe760760f6",
          "sha256": "f83be84b35df6dbcf7304b5227a22f6a4a353e17600d805610f7581fa9407333",
          "sha1": "3280f3e56b95ede61c50736291ca7607d2586c28",
          "md5": "8e9a7b1f03305d022fb746093999a3fa"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-unit-macosx64-1.10.3-picture-cache.2-sources.jar",
          "url": "ui-unit-macosx64-1.10.3-picture-cache.2-sources.jar",
          "size": 33594,
          "sha512": "360e2fc9c8f62bba86f0e928ff8f61087149b616c1335b58f200bb73fabbbde88e6f3dfd6bc9ac28ffc72df4bce35618f3f0261460d1ef17dc28ee9f255db466",
          "sha256": "fabed03aa9375fac42c9f4dc8f13734c500950371904a6f2eaf22b3b2a088c42",
          "sha1": "552859ce495664d56726fde8c4c1f3a772ddcf05",
          "md5": "0d2f081da1941af2510c011841671769"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-macosx64-1.10.3-picture-cache.2-metadata.jar",
          "url": "ui-unit-macosx64-1.10.3-picture-cache.2-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}