{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-test-junit4/1.10.3-picture-cache.1/ui-test-junit4-1.10.3-picture-cache.1.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-test-junit4",
    "version": "1.10.3-picture-cache.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-desktop-1.10.3-picture-cache.1.jar",
          "url": "ui-test-junit4-desktop-1.10.3-picture-cache.1.jar",
          "size": 34450,
          "sha512": "05b60896a0b9d97bd6cdfb1fd353628f131dcea48605853913395a0a4b02daac4249fa09573595149e056b19628880bfd073e2b83447b8c8cff752f49f95b5ba",
          "sha256": "de2f63543b8f646b85c789e3bf53121e4e6d89d3c7c0afc0358954cc27316a71",
          "sha1": "d79788278e7d36ad808b4148a5094c0b85ae9240",
          "md5": "34f4ea6e665b9080c06a52fa97de7a72"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko-awt",
          "version": {
            "requires": "0.9.37.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-desktop-1.10.3-picture-cache.1.jar",
          "url": "ui-test-junit4-desktop-1.10.3-picture-cache.1.jar",
          "size": 34450,
          "sha512": "05b60896a0b9d97bd6cdfb1fd353628f131dcea48605853913395a0a4b02daac4249fa09573595149e056b19628880bfd073e2b83447b8c8cff752f49f95b5ba",
          "sha256": "de2f63543b8f646b85c789e3bf53121e4e6d89d3c7c0afc0358954cc27316a71",
          "sha1": "d79788278e7d36ad808b4148a5094c0b85ae9240",
          "md5": "34f4ea6e665b9080c06a52fa97de7a72"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-test-junit4-desktop-1.10.3-picture-cache.1-sources.jar",
          "url": "ui-test-junit4-desktop-1.10.3-picture-cache.1-sources.jar",
          "size": 15620,
          "sha512": "259f0f817b96fd13b75b4494f7deb2a980b396389454ca14405f4226b224c2d7e6d233c24dddc44cdeeef89787befdc524817e07a9c3a35f053ee38e2156cade",
          "sha256": "68c9f917539c2f29ae45ba1a0d79a487491be7c32df7d3abc305c61e50e3ce75",
          "sha1": "7b81d85c5774805c1b17381d01823b0dcf201d6c",
          "md5": "2c4a73942343cedb0d7aeea5c581641c"
        }
      ]
    }
  ]
}