{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.material3",
    "module": "material3-window-size-class",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-9999.0.0-SNAPSHOT.jar",
          "url": "material3-window-size-class-9999.0.0-SNAPSHOT.jar",
          "size": 7729,
          "sha512": "8fcc6681a3e8f1ef9054284c85a626665554ca758586f012c5a9c2178a8759a3e57227d32895c91800395b9dde40f7987efe32785d849efd1cb1cf983077fdc0",
          "sha256": "e6b6ae8e3a0e57d5ef6c1c420caf7858054cd8f5f1e92a72b88c9ccd10aeef52",
          "sha1": "f317b8de470fb0e04049e1bd6cad4f0d05bc481d",
          "md5": "9c90ba6c42e4227abb8bcb9356cf6053"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "material3-window-size-class-9999.0.0-SNAPSHOT-sources.jar",
          "url": "material3-window-size-class-9999.0.0-SNAPSHOT-sources.jar",
          "size": 9563,
          "sha512": "d80cb17dc11945f4d5abc95781037c8b521c9677afc3b53917af84cea151ccc41f3ef41b95156896a6af84f2fcaa40e7ee82a18f95e6efe4cc875bc189f603f4",
          "sha256": "04370b54abe4f5bef4ab48b9985513388c7eebeb2d7a0d522eae7a976893bf23",
          "sha1": "8019ff8653913ef6f2452ebb12ed642c8bb044a3",
          "md5": "eaf78356a9a841c87358a1ab2a9f9de9"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.3"
          }
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ]
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha08"
          }
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.3"
          }
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha08"
          }
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-desktop/9999.0.0-SNAPSHOT/material3-window-size-class-desktop-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-desktop",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-desktop/9999.0.0-SNAPSHOT/material3-window-size-class-desktop-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-desktop",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-desktop/9999.0.0-SNAPSHOT/material3-window-size-class-desktop-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-desktop",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../material3-window-size-class-js/9999.0.0-SNAPSHOT/material3-window-size-class-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../material3-window-size-class-js/9999.0.0-SNAPSHOT/material3-window-size-class-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../material3-window-size-class-js/9999.0.0-SNAPSHOT/material3-window-size-class-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-macosarm64/9999.0.0-SNAPSHOT/material3-window-size-class-macosarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-macosarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-macosarm64/9999.0.0-SNAPSHOT/material3-window-size-class-macosarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-macosarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-macosarm64/9999.0.0-SNAPSHOT/material3-window-size-class-macosarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-macosarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-macosx64/9999.0.0-SNAPSHOT/material3-window-size-class-macosx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-macosx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-macosx64/9999.0.0-SNAPSHOT/material3-window-size-class-macosx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-macosx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-macosx64/9999.0.0-SNAPSHOT/material3-window-size-class-macosx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-macosx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-uikitarm64/9999.0.0-SNAPSHOT/material3-window-size-class-uikitarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-uikitarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-uikitarm64/9999.0.0-SNAPSHOT/material3-window-size-class-uikitarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-uikitarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-uikitarm64/9999.0.0-SNAPSHOT/material3-window-size-class-uikitarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-uikitarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-uikitsimarm64/9999.0.0-SNAPSHOT/material3-window-size-class-uikitsimarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-uikitsimarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitSimArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-uikitsimarm64/9999.0.0-SNAPSHOT/material3-window-size-class-uikitsimarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-uikitsimarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-uikitsimarm64/9999.0.0-SNAPSHOT/material3-window-size-class-uikitsimarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-uikitsimarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-uikitx64/9999.0.0-SNAPSHOT/material3-window-size-class-uikitx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-uikitx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-uikitx64/9999.0.0-SNAPSHOT/material3-window-size-class-uikitx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-uikitx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-window-size-class-uikitx64/9999.0.0-SNAPSHOT/material3-window-size-class-uikitx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-uikitx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../material3-window-size-class-wasm-js/9999.0.0-SNAPSHOT/material3-window-size-class-wasm-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-wasm-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../material3-window-size-class-wasm-js/9999.0.0-SNAPSHOT/material3-window-size-class-wasm-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-wasm-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../material3-window-size-class-wasm-js/9999.0.0-SNAPSHOT/material3-window-size-class-wasm-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3",
        "module": "material3-window-size-class-wasm-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    }
  ]
}