{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-graphics/1.10.3-picture-cache.2/ui-graphics-1.10.3-picture-cache.2.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-graphics",
    "version": "1.10.3-picture-cache.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.37.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-macosX64Main-1.10.3-picture-cache.2.klib",
          "url": "ui-graphics-macosx64-1.10.3-picture-cache.2.klib",
          "size": 789574,
          "sha512": "7757098e5eddd82b3c1ec2a638d6096d2be3747306c976b7f8883731e666ac4803be815e38b4e90e2c4e185056ed6b36a87a3f1dfc95a6c0174a5f1ecd8af877",
          "sha256": "b66ef58c0afe70cd71451c3ebf4f1e69ceadfa04cd01cac37e88cecf24442af2",
          "sha1": "fedc489a6f4e98e6202e1cc29a1c1cf633937778",
          "md5": "bd9733804fb2665566afe14a518445f6"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-graphics-macosx64-1.10.3-picture-cache.2-sources.jar",
          "url": "ui-graphics-macosx64-1.10.3-picture-cache.2-sources.jar",
          "size": 244191,
          "sha512": "a5cf0c5ccd29d60b91a5917d06c9de2fe3d762bd6011ff6b1016a52227fb42477c803edf1473fb5517c4d05bb52416a65972143c637d6ab346b7851f40e73354",
          "sha256": "24f517aad8c4476b64e7381abfbc518d291c457e70ffb0eb48c66f654feeabe3",
          "sha1": "639e745040c98134e4ecb8cf159d6f3525f170c2",
          "md5": "fdc2a021bdee3bfe946322d9a7a0b70f"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.37.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-macosx64-1.10.3-picture-cache.2-metadata.jar",
          "url": "ui-graphics-macosx64-1.10.3-picture-cache.2-metadata.jar",
          "size": 2548,
          "sha512": "d3ec08bba325293f24c1fdb69fec582d0f405cbe88340556b276aac48b2ca4a00909948e89b4cb36aea10da8220448414a70706330eb8e17ddf4c7e2cbccd7f5",
          "sha256": "41876eb4839990a46029c92480691aa341210b68794dc43ea9133cfefae65785",
          "sha1": "bc5fe7d9857f12e65f118a5650d072794b99dac7",
          "md5": "ec529c0a72a5a23e19ebe91d8a016d22"
        }
      ]
    }
  ]
}