{
  "formatVersion": "1.1",
  "component": {
    "url": "../../adaptive/9999.0.0-SNAPSHOT/adaptive-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material3.adaptive",
    "module": "adaptive",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.window",
          "module": "window-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-uikitX64Main-9999.0.0-SNAPSHOT.klib",
          "url": "adaptive-uikitx64-9999.0.0-SNAPSHOT.klib",
          "size": 30044,
          "sha512": "70f3ce56617b712be9a85ddd5e50175f61c9799c873915499a61137b5ed9e1b0414ceeb46c8f54dfc0ea2892b35de0880892712524fce26c2f52c362fbe19664",
          "sha256": "f0165e2493d088637180c04418a70fd015e9ef039fac80ffd0b79b533c63c786",
          "sha1": "6325d3cee81115ce23da5dc8046813b9de8cadcc",
          "md5": "d1fcc2c17b9bdaebd074dadb075e4796"
        }
      ]
    },
    {
      "name": "uikitX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "adaptive-uikitx64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "adaptive-uikitx64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 10465,
          "sha512": "043cc011d409600ec20af015664b551f71e676a7aab7555bff14842a0a24d62755d412c49111d66a374c325d898b8ddbab152e0ec600b727d6399fab6bb05fdf",
          "sha256": "36c942eb377d47523a8f7b9c801c282caaa354505e8347aa61504fe2682d040c",
          "sha1": "864bfcd3fbbcb35e2a5454820675e6eddcf54978",
          "md5": "23a48eebc6f9dd8f2266b85558cec071"
        }
      ]
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.window",
          "module": "window-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-uikitx64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "adaptive-uikitx64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}