{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/9999.0.0-SNAPSHOT/foundation-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.foundation",
    "module": "foundation",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.37.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-macosArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "foundation-macosarm64-9999.0.0-SNAPSHOT.klib",
          "size": 4156927,
          "sha512": "a90b49bdf8d8a8fa02888e65b01f5b31f76e8e7f8c0069a89e45395238bfc44d2368b389ec844d0b39a8710d6628327470c8e2df600063e9e2d81be424377d6e",
          "sha256": "23ea80106fce94d38ef127bda9b02155b93bdf8fb98b923848ab6bb0c1c243d6",
          "sha1": "370419e09408d4d72f4232a06c01caa4c1a36488",
          "md5": "8a18645b5cf24ac41ae15268377916a3"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "foundation-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "foundation-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 1077048,
          "sha512": "35680cc394c576574fdbbb1e4e3134219232f048d207ca52c3748c0de09bf312b19430699ca0f21b61b66eef23a0ab2096771baa5146ac68cfe95c3e573538fc",
          "sha256": "501b2534f170d5a0d4400d3290ae7fca29cbd8d38e9130731a7a06574473a9ea",
          "sha1": "60484781bfd7ecdc6ad7fa4db3dfe0375a1d9a9b",
          "md5": "e00ebc1dabae56874768a19ca131af22"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.37.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "foundation-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 51360,
          "sha512": "cfb509201a99a648385255d2a5abb3dc93b29131d43db56643a76913538b14a58b4e6dbc3ecbc1bbc82359fd3d9bf320d28036796a6674e25b5bab584febd450",
          "sha256": "5473ded3ba4e6635e93e293b9e7ed8c3d5d79b4a7f843315a9ce31b5e86a5468",
          "sha1": "5970a883274871146c405875340231a22254a0ee",
          "md5": "28da5d2cb61caaef90e769f56f2527f8"
        }
      ]
    }
  ]
}