{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-geometry/1.10.3-picture-cache.2/ui-geometry-1.10.3-picture-cache.2.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-geometry",
    "version": "1.10.3-picture-cache.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-uikitArm64Main-1.10.3-picture-cache.2.klib",
          "url": "ui-geometry-uikitarm64-1.10.3-picture-cache.2.klib",
          "size": 70764,
          "sha512": "b2ec7fd644a728c8919c84308dd13acefb39a595b8fa37d2cac98238f3079e526cf8a4a583467fe426b46bc4ffbf71a6ee38a632999ca8f2733ba0786b4cf3aa",
          "sha256": "7e492b4d555eb4bc0af8bd0260e3939941f0eb96ee5ad5dd50ce2362e4f8c5a8",
          "sha1": "0aef2bd64dd6f494edcfa5732089dedcc4469d3d",
          "md5": "7043c80b6e77874e62823e4662fbf4cc"
        }
      ]
    },
    {
      "name": "uikitArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-geometry-uikitarm64-1.10.3-picture-cache.2-sources.jar",
          "url": "ui-geometry-uikitarm64-1.10.3-picture-cache.2-sources.jar",
          "size": 21319,
          "sha512": "f01304f72a64d4f4501ecc2f07ed0e8507277c1c599e7c1c32cd50236504fd0d489a67f18caca2fb4464f213fdc49186cc10cf28dd1c6bd8b87ae1dee81189c8",
          "sha256": "4d1dab1b80fc0a3a71db085c6cdfb7957a14f58e23686f2963a53968e51197d1",
          "sha1": "d899607f8e22d9157de20bbea84b2a25956ddeb2",
          "md5": "98913000dba90df69c0637ba13448014"
        }
      ]
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-uikitarm64-1.10.3-picture-cache.2-metadata.jar",
          "url": "ui-geometry-uikitarm64-1.10.3-picture-cache.2-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}