{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-util/1.10.3-picture-cache.1/ui-util-1.10.3-picture-cache.1.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-util",
    "version": "1.10.3-picture-cache.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-macosX64Main-1.10.3-picture-cache.1.klib",
          "url": "ui-util-macosx64-1.10.3-picture-cache.1.klib",
          "size": 40145,
          "sha512": "72ba96435c08dd58098a0b01c42b0817773ef8a27e6cd0075b318777bea050b3b4b818659423f35c56b4347c8b3659ba52ee86214913d9abb3c0c0548ea02988",
          "sha256": "0ab42b9915e407b3471c0ce0a446455f01b3a3cb34df81f3d73bb35f5a09e76f",
          "sha1": "ac19fca9f493bc0021b7f209710ac5cd7acd5ad6",
          "md5": "68c9216efd51b5d05213a9e14eb1d6d5"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-util-macosx64-1.10.3-picture-cache.1-sources.jar",
          "url": "ui-util-macosx64-1.10.3-picture-cache.1-sources.jar",
          "size": 15162,
          "sha512": "6d09f845139caf9abc68468b85c2c18881e6999328cca3ef8dadd822e0e188fe21aa7336b587bf4dd79a122dea6d10d0c18cef180a228fa68a1b301dcbcd2850",
          "sha256": "4d95ffdf96789d8fce645c8f2a9d6df889a8bdc05072dfda9754ca202785e66d",
          "sha1": "f5c6ec396f3b1ac3e067c679fe0eef2e3deb6f1a",
          "md5": "8e2b4735a591c7585b3c4810d9d30b0e"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-macosx64-1.10.3-picture-cache.1-metadata.jar",
          "url": "ui-util-macosx64-1.10.3-picture-cache.1-metadata.jar",
          "size": 4927,
          "sha512": "f00518fcc49350b8f32ea19ba8bbaf0eac558d0b8735afee7e76a088a8feb59d944da826302cabd0820731f52b62c832830a274d316b46429b98d34afdd82b27",
          "sha256": "e857fdfacfcaf914f0455d08dbd77d27bdf27552b1bbebfc875d8ea29e66f505",
          "sha1": "b568e21b3055f020451d334afaba56d4a68ec154",
          "md5": "29fe20186f0ec3dd1a2029d5856318c6"
        }
      ]
    }
  ]
}