{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling-preview/9999.0.0-SNAPSHOT/ui-tooling-preview-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-tooling-preview",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-macosArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "ui-tooling-preview-macosarm64-9999.0.0-SNAPSHOT.klib",
          "size": 38279,
          "sha512": "5b3e26f25e16db0e3020d5040d43a113ebdd978f5eaf2f0c42acf43bdf8cb71090f8e21cde427085ab6c44f966e1a136ee95e60bba76b1ec9bc61dfc74ca00c4",
          "sha256": "a12f833abe068e9ee2d02a3ba3f688f655245489ee0bbc748e1feed923d9345a",
          "sha1": "6810bacc2b64dfbaaae03cb776c638f7e4b46d84",
          "md5": "79c65245cce089a9707e127b793f2c51"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-tooling-preview-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-tooling-preview-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 14792,
          "sha512": "7e81a8b72d4bf301060ba249e473e5cb09cbab322d2ad529a52a2a24016f73d71dc485cbe2cabf11a396de93615d90e081c455519d623c34f0cdeca225386829",
          "sha256": "b2038f7dd5180f2daa1231af8ea15afa21fce47df690633f3f43c25e9420c7d9",
          "sha1": "735f70e90bb515403838df821119a3216e7311aa",
          "md5": "4f2f7d345181895b6a872b4e281f108a"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "ui-tooling-preview-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}