{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.10.3-picture-cache.1/foundation-1.10.3-picture-cache.1.module",
    "group": "org.jetbrains.compose.foundation",
    "module": "foundation",
    "version": "1.10.3-picture-cache.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.37.4"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-desktop-1.10.3-picture-cache.1.jar",
          "url": "foundation-desktop-1.10.3-picture-cache.1.jar",
          "size": 4314315,
          "sha512": "9617b16eb194a3988f05dc05e4defb6693e5dc3ad90bb4b80a6911e174ff9c46374fe2886c1418b2a3314b72c3f80585d11a46d3928606244ca18554e0092516",
          "sha256": "3a9b7bfae72f1a92a8123d3290bb7d7f61d92e5cde877af5373c3e5c2caceb2b",
          "sha1": "0d9ba57abee3527886ea640d3b390a70ba9e28af",
          "md5": "70d7b34e8681a374ed1ed640c3ba8c11"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.37.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-desktop-1.10.3-picture-cache.1.jar",
          "url": "foundation-desktop-1.10.3-picture-cache.1.jar",
          "size": 4314315,
          "sha512": "9617b16eb194a3988f05dc05e4defb6693e5dc3ad90bb4b80a6911e174ff9c46374fe2886c1418b2a3314b72c3f80585d11a46d3928606244ca18554e0092516",
          "sha256": "3a9b7bfae72f1a92a8123d3290bb7d7f61d92e5cde877af5373c3e5c2caceb2b",
          "sha1": "0d9ba57abee3527886ea640d3b390a70ba9e28af",
          "md5": "70d7b34e8681a374ed1ed640c3ba8c11"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "foundation-desktop-1.10.3-picture-cache.1-sources.jar",
          "url": "foundation-desktop-1.10.3-picture-cache.1-sources.jar",
          "size": 1093173,
          "sha512": "17ca5b518249954bc197aed92a8faefde22f7f35a1c0f3b4f65b61ae1835875c1d31b939baf73d7d3e835f4c39f0cc06a408d96a5502682291f0b49c9920cc82",
          "sha256": "b06167fd914eb3fe19b46a85e62add1ab22889f66a00897a3cc7e7cf4cbce0a4",
          "sha1": "0fb2a7f718bc5fb7320e4804f49e9993b0d69e2d",
          "md5": "c90a9e9760cfb22641870329cf6804d1"
        }
      ]
    }
  ]
}