{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/9999.0.0-SNAPSHOT/material-ripple-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material",
    "module": "material-ripple",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-macosX64Main-9999.0.0-SNAPSHOT.klib",
          "url": "material-ripple-macosx64-9999.0.0-SNAPSHOT.klib",
          "size": 61720,
          "sha512": "85776693d3ea23226a8252d4fa1ed40570fca6de1a98adad42baed03532f991b0a634e4c8243d0f07e3552914a8590034a4b88f72716335dfc1381322760f6c4",
          "sha256": "8cc6f772c6f97985b409e85ac6e1e7faf3eee2a1a0abbdba6321a94746c2e136",
          "sha1": "12cde49e1382b770d893000eb4c8bc38c262ac91",
          "md5": "981c444237c870c9602ecc0e4c01496c"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "material-ripple-macosx64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "material-ripple-macosx64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 15269,
          "sha512": "74fa1de4d5b538cdf1649a5d3d6d0b3577b64b6b2db1836319dbc50a16a74c7fc5865625189ae62200deab39944561d80d131574e233621de3804acbfbb9ecee",
          "sha256": "925a415f7b0472ce74f50a7b7c457348016f1f7642afcc5ac2488ab5efd8d23a",
          "sha1": "2b1d7b769dfd53c82e7e225aa5409ac889aaa150",
          "md5": "90ed31fb7e33bfdd1c232be709066733"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-macosx64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "material-ripple-macosx64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}