{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-backhandler/1.10.3-picture-cache.1/ui-backhandler-1.10.3-picture-cache.1.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-backhandler",
    "version": "1.10.3-picture-cache.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-backhandler-release.aar",
          "url": "ui-backhandler-android-1.10.3-picture-cache.1.aar",
          "size": 4282,
          "sha512": "3b58963dc16519decb6d29e4c5219513e7dd934b7d4ead1c19e0123f7e0ba8d433579aefc4d6db09294fd78c99178165a9aacc8af815ddf8bc1e990e7a00dce9",
          "sha256": "d6dd4503f2337976bab5773aeeb7c2b536e6bfecd55c0066cc3174593b11957f",
          "sha1": "a0bda0636718c164664f2272f94cc39fac61f74c",
          "md5": "a39d53b93cd4f4a945297a162c96cbdc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-backhandler-release.aar",
          "url": "ui-backhandler-android-1.10.3-picture-cache.1.aar",
          "size": 4282,
          "sha512": "3b58963dc16519decb6d29e4c5219513e7dd934b7d4ead1c19e0123f7e0ba8d433579aefc4d6db09294fd78c99178165a9aacc8af815ddf8bc1e990e7a00dce9",
          "sha256": "d6dd4503f2337976bab5773aeeb7c2b536e6bfecd55c0066cc3174593b11957f",
          "sha1": "a0bda0636718c164664f2272f94cc39fac61f74c",
          "md5": "a39d53b93cd4f4a945297a162c96cbdc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ui-backhandler-android-1.10.3-picture-cache.1-sources.jar",
          "url": "ui-backhandler-android-1.10.3-picture-cache.1-sources.jar",
          "size": 5412,
          "sha512": "4de719d41896aa8c6320b709e0c5a13dc079510b0d41ddfbf3627823b23e4fc46c54f1a8a40e925af26249078b65a9f07c9cd70e8a7e9dd7b14f31a34eb28af6",
          "sha256": "510bb91008a00a5090beb2484b757fd5b15c2011f955098f6699314ad17e598a",
          "sha1": "c07e4ce2fc30aa23e2a0ac3941e7e8dcc8986cf5",
          "md5": "6d86afef6d369174c163d5312a2edee6"
        }
      ]
    }
  ]
}