{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-backhandler/1.10.3-picture-cache.1/ui-backhandler-1.10.3-picture-cache.1.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-backhandler",
    "version": "1.10.3-picture-cache.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-backhandler-debug.aar",
          "url": "ui-backhandler-android-debug-1.10.3-picture-cache.1.aar",
          "size": 4401,
          "sha512": "473c7a514dfab51af0a88648542ebfec6685e10a2d71c78fa8f947b7ddabbde167f9c41d0479bf44a88ef457db0fbaa008c791a77fd577b94e0c58d8f983c007",
          "sha256": "434a8a5602fbb418dadeea34c8c8c53562dc6fdc953ed9f008a7c7075586791b",
          "sha1": "f9cf4f2b0babf42d5700aff2010f3b0d078c4406",
          "md5": "63590cb85d9ca228f182f927e0141bcd"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-backhandler-debug.aar",
          "url": "ui-backhandler-android-debug-1.10.3-picture-cache.1.aar",
          "size": 4401,
          "sha512": "473c7a514dfab51af0a88648542ebfec6685e10a2d71c78fa8f947b7ddabbde167f9c41d0479bf44a88ef457db0fbaa008c791a77fd577b94e0c58d8f983c007",
          "sha256": "434a8a5602fbb418dadeea34c8c8c53562dc6fdc953ed9f008a7c7075586791b",
          "sha1": "f9cf4f2b0babf42d5700aff2010f3b0d078c4406",
          "md5": "63590cb85d9ca228f182f927e0141bcd"
        }
      ]
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ui-backhandler-android-debug-1.10.3-picture-cache.1-sources.jar",
          "url": "ui-backhandler-android-debug-1.10.3-picture-cache.1-sources.jar",
          "size": 5412,
          "sha512": "4de719d41896aa8c6320b709e0c5a13dc079510b0d41ddfbf3627823b23e4fc46c54f1a8a40e925af26249078b65a9f07c9cd70e8a7e9dd7b14f31a34eb28af6",
          "sha256": "510bb91008a00a5090beb2484b757fd5b15c2011f955098f6699314ad17e598a",
          "sha1": "c07e4ce2fc30aa23e2a0ac3941e7e8dcc8986cf5",
          "md5": "6d86afef6d369174c163d5312a2edee6"
        }
      ]
    }
  ]
}