{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-graphics/9999.0.0-SNAPSHOT/ui-graphics-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-graphics",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.37.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-macosArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "ui-graphics-macosarm64-9999.0.0-SNAPSHOT.klib",
          "size": 789587,
          "sha512": "ab3f2f95958457e62b718a31c0960e3ae4d85928d14d321f2d2480f4ee417516a7cebc2029490d832df901e2b60cbaf6b8e83e345fe536bbcfbec3c64aacea92",
          "sha256": "abc8828e1495fa4023da1338ae28ebcf72c0bdeaa2313d8b9b261fc7499f8ef3",
          "sha1": "fd02f0ac5843256e193273662db4dc52575d9280",
          "md5": "3b1e4ea49a8088aafe3362ae4f4b2680"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-graphics-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-graphics-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 244191,
          "sha512": "a5cf0c5ccd29d60b91a5917d06c9de2fe3d762bd6011ff6b1016a52227fb42477c803edf1473fb5517c4d05bb52416a65972143c637d6ab346b7851f40e73354",
          "sha256": "24f517aad8c4476b64e7381abfbc518d291c457e70ffb0eb48c66f654feeabe3",
          "sha1": "639e745040c98134e4ecb8cf159d6f3525f170c2",
          "md5": "fdc2a021bdee3bfe946322d9a7a0b70f"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.37.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "ui-graphics-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 2548,
          "sha512": "d3ec08bba325293f24c1fdb69fec582d0f405cbe88340556b276aac48b2ca4a00909948e89b4cb36aea10da8220448414a70706330eb8e17ddf4c7e2cbccd7f5",
          "sha256": "41876eb4839990a46029c92480691aa341210b68794dc43ea9133cfefae65785",
          "sha1": "bc5fe7d9857f12e65f118a5650d072794b99dac7",
          "md5": "ec529c0a72a5a23e19ebe91d8a016d22"
        }
      ]
    }
  ]
}