{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-graphics/1.10.3-picture-cache.2/animation-graphics-1.10.3-picture-cache.2.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation-graphics",
    "version": "1.10.3-picture-cache.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-uikitSimArm64Main-1.10.3-picture-cache.2.klib",
          "url": "animation-graphics-uikitsimarm64-1.10.3-picture-cache.2.klib",
          "size": 68439,
          "sha512": "6d475ec38d7cc87dfc5ffc79b031a9498e7dcc20309ee3b0ea2cc50c237e7e043c470e8689921705d7b8f46aee19ef0497943792c975183c97ec066cf2cf7335",
          "sha256": "50b2a13c7b366339f44794fd56ef7c47a3376dd2b1a6e07a2c8f0f7afe61f2b6",
          "sha1": "71c4168e6105fc7eafe5421282d4effad4c55550",
          "md5": "a37c3e3839a4cde357ac41bf16d76a38"
        }
      ]
    },
    {
      "name": "uikitSimArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "animation-graphics-uikitsimarm64-1.10.3-picture-cache.2-sources.jar",
          "url": "animation-graphics-uikitsimarm64-1.10.3-picture-cache.2-sources.jar",
          "size": 9790,
          "sha512": "1614c534ef907c08a28efd116ff824e1a3563d55a2ed765158d57d22ee9330aec688263d9cf83257afd1543ee679a0ce37ca0fe5d5cdef9ea6ec8bbc544a3707",
          "sha256": "d3740faffd94db014fab408ea7944174d160873541268eb03f6d2dcb5a90e4d7",
          "sha1": "74ee6d86e258687aeed75cc50a19c66e29a39511",
          "md5": "49bbdfd72a81fb7912a079947dd39dda"
        }
      ]
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.3-picture-cache.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-uikitsimarm64-1.10.3-picture-cache.2-metadata.jar",
          "url": "animation-graphics-uikitsimarm64-1.10.3-picture-cache.2-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}